import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Header from "@/components/shared/Header/header";
import Footer from "@/components/shared/footer/footer";
import AppProvider from "@/components/provider/AppProvider";
import AuthProvider from "@/components/provider/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <AuthProvider>
          <AppProvider>
            <Header />
            {children}
            <Toaster position="top-right" />
            <Footer />
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
